-- =============================================================
-- Seed Data — Paste into Supabase SQL Editor AFTER running setup
-- =============================================================
-- This inserts all 190+ contacts from your original spreadsheet.
-- =============================================================

INSERT INTO contacts (name, title, company, dri, support, status, priority, last_contact, contact_date, source, project, notes, phone, email, pitch_status) VALUES
('David Ladouceur', 'Managing Director', 'place.fund', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '17204017165', 'dave@place.fund', 'Pitched previously'),
('Spencer Morris', 'Chief Investment Officer', 'The Allen Morris company', 'Tony Cho', 'Michael Weil', '', 'HOT', 'Email', '2025-03-04', '', 'PHX JAX', '', '', 'WASM@allenmorris.com', 'Pitched previously'),
('Tripp Gulliford', '', 'Aspect Real Estate Group', 'Michael Weil', 'Duarte Melo Ribeiro', '', 'HOT', 'Email', '2025-01-29', 'Sam Middlekauf', 'PHX JAX', '', '19049550003', 'Tgulliford@aspect-re.com', 'Pitched previously'),
('Benjamin Small', 'Head of Real Estate', 'ESJ CAPITAL PARTNERS', 'Michael Weil', '', '', 'HOT', 'Text/ WhatsApp', '2025-03-04', 'Tony Cho', 'PHX JAX', 'Setzer acquisition', '', 'bs@esj.us', 'Pitched previously'),
('Daniel Schor', 'Partner', 'AJ Capital Partners', '', '', '', 'HOT', 'In person', NULL, 'Ilan Marcoschamer', 'PHX JAX', 'Interested in visiting JAX', '13123307750', 'ds@ajcpt.com', 'Pitched previously'),
('David Beall', 'Franchisee', 'pinkberry.com', 'Tony Cho', '', '', 'WARM', 'Email', NULL, '', 'PHX JAX', 'investor prospect', '18658039214', 'david.beall@me.com', 'Pitched previously'),
('Joseph Deitch', 'Founder', 'elevateprize.org', 'Tony Cho', 'Michael Weil', '', 'WARM', 'In person', NULL, '', 'PHX JAX', '', '16174620955', 'joe@elevateprize.org', 'Pitched previously'),
('Eric Schulze', 'Commercial Real Estate Consultant', 'reschulzecre.com', 'Tony Cho', 'Brendan McKeon', 'Pitched', 'WARM', 'Email', '2025-03-10', '', 'PHX JAX', '', '', 'reschulze@reschulzecre.com', 'Pitched previously'),
('Ralph Davies', 'Chief Financial Officer', 'Assouline-Busch Capital', 'Tony Cho', 'Michael Weil, Brendan McKeon', '', 'HOT', 'Email', '2025-04-22', '', 'PHX JAX', '', '', 'ralph.davies.jr@gmail.com', 'Pitched previously'),
('Chris McTammany', 'Managing Director', 'velocityhealth.com', 'Tony Cho', 'Michael Weil', '', 'HOT', 'Zoom Call', '2025-03-26', 'Matt Chang', 'PHX JAX', '', '13103679120', 'chris@velocityhealth.com', 'Pitched previously'),
('Eyal Peretz', 'CEO', 'Fuse Group Investment Companies', 'Tony Cho', '', '', 'COLD', 'Email', '2025-03-06', '', 'PHX JAX', '', '13053215131', 'eyal@fusegroupco.com', 'Pitched previously'),
('Jeffrey Davis', 'Managing Director', 'eastdilsecured.com', '', '', '', 'HOT', '', NULL, 'Ilan Marcoschamer', 'PHX JAX', '', '19178823314', 'jdavis@eastdilsecured.com', 'Pitched previously'),
('Marcus Davis', 'Acquisition Specialist', 'blueskycommunities.com', 'Michael Weil', 'Brendan McKeon', '', 'HOT', 'Email', NULL, 'Omar Sobhy', 'PHX JAX', '', '14075793166', 'mdavis@blueskycommunities.com', ''),
('Shawn Wilson', 'President and Chief Executive Officer', 'blueskycommunities.com', 'Michael Weil', 'Brendan McKeon', '', 'HOT', 'In person', NULL, 'Omar Sobhy', 'PHX JAX', '', '', 'swilson@blueskycommunities.com', 'Pitched previously'),
('Geoffrey Harlan', 'Vice President of Acquisitions', 'blueskycommunities.com', 'Michael Weil', 'Brendan McKeon', '', 'HOT', 'Zoom Call', NULL, 'Omar Sobhy', 'PHX JAX', '', '18133688592', 'gharlan@blueskycommunities.com', ''),
('Mark Ellert', 'President', 'Guy Harvey Resort', 'Michael Weil', 'Brendan McKeon', '', 'HOT', 'Zoom Call', NULL, 'David Lukes', 'PHX JAX', '', '13057251060', 'mhellert@guyharveyoutpost.com', 'Pitched previously'),
('Jack Weir', 'President/ Owner', 'eastwinddevelopment.com', '', '', '', 'COLD', '', NULL, 'David Lukes', 'PHX JAX', '', '', 'jweir@eastwinddevelopment.com', 'Pitched previously'),
('Bjarne Borg', 'Co-Founder & Executive Chairman', 'indexinvest.com', 'Michael Weil', 'Brendan McKeon', 'Partnership in progress', 'HOT', 'Zoom Call', NULL, 'David Lukes', 'PHX JAX', '', '15614274920', 'bjarne.borg@indexinvest.com', 'Pitched previously'),
('Scott Hobby', 'Managing Partner', 'Corner Lot Living', 'Michael Weil', 'Brendan McKeon', '', 'WARM', 'Zoom Call', NULL, 'Tripp Gulliford, III', 'PHX JAX', '', '19045217122', 'scott@hobbycollc.com', 'Pitched previously'),
('Robert Cox', 'Managing Director, Community Lending', 'reinvestment.com', 'Brendan McKeon', 'Michael Weil', '', 'HOT', 'Zoom Call', NULL, 'Omar Sobhy', 'PHX JAX', '', '', 'Robert.Cox@reinvestment.com', ''),
('David Doll', 'Managing Director', 'morganstanley.com', 'Tony Cho', '', '', 'HOT', '', NULL, 'Dawn Mussalem', 'PHX JAX', '', '19044603422', 'David.Doll@morganstanley.com', 'Pitched previously'),
('Jud Ireland', 'Partner & Creative Director', 'Multicore Intl.', 'Tony Cho', '', '', 'WARM', 'Email', '2025-02-14', '', 'PHX JAX', '', '', 'jp.ireland@gmail.com', 'Pitched previously'),
('Greg Carson', 'Founder', 'Derabit XBTO', 'Tony Cho', 'Michael Weil', 'Funded', 'WARM', 'Phone call', '2025-02-12', '', 'PHX JAX', '', '', 'greg@humla.vc', 'Pitched previously'),
('Harold Fort', '', 'hexagon.partners', 'Michael Weil', 'Brendan McKeon', '', 'COLD', 'In person', '2025-02-06', '', 'PHX JAX', 'aqruitechtonica', '7862465619', 'hfort@hexagon.partners', 'Pitched previously'),
('Ken Grimes', 'Senior Managing Director and Partner', 'pattersonreag.com', 'Michael Weil', '', '', 'COLD', 'Email', '2025-01-31', '', 'PHX JAX', '', '14045046685', 'kgrimes@pattersonreag.com', 'Pitched previously'),
('Billy Zeits', 'Vice President of Government Affairs', 'Corner Lot Development', 'Michael Weil', 'Emily Moody', '', 'COLD', 'Email', '2025-01-16', 'Michael Weil', 'PHX JAX', 'Corner Lot looking at Dev site A&B', '19048141299', 'wzeits@cornerlotdevelopment.com', 'Pitched previously'),
('Brad Colmer', 'Founder', 'decocapital.com', 'Tony Cho', 'Michael Weil', '', 'COLD', 'Email', '2025-01-27', 'Tony Cho', 'PHX JAX', '', '13057992465', 'bradley.colmer@decocapital.com', 'Pitched previously'),
('Kareem Brantley', 'Principal – Florida Markets', 'integral-online.com', 'Michael Weil', '', '', 'WARM', 'Email', '2025-03-14', 'Ken Grimes', 'PHX JAX', '', '13052067018', 'kbrantley@integral-online.com', 'Pitched previously'),
('Eric Amyot', 'CEO & Cofounder', 'Keystone Species Co.', 'Tony Cho', '', '', 'COLD', 'Email', '2025-02-08', '', 'PHX JAX', 'Cofounder of Keystone Species Co.', '19702059195', 'eric@keystonespecies.co', 'Pitched previously'),
('Nick Yee', 'Chief Innovation Officer', 'issho.house', 'Tony Cho', '', '', 'COLD', 'Email', '2025-02-08', '', 'PHX JAX', 'Cofounder of Keystone Species Co.', '', 'nick@issho.house', 'Pitched previously'),
('Jonathan Donahue', 'CEO', 'ai.writelabel.com', 'Tony Cho', '', '', 'HOT', 'In person', '2025-02-06', 'RTU Screening @ The HUB', 'PHX JAX', 'Palm Beach - grants for affordable housing', '', 'james.n.donahue@gmail.com', 'Pitched previously'),
('Eric Fuller', 'Co-Owner', 'deccalive.com', '', '', '', 'HOT', '', NULL, '', 'PHX JAX', 'Connection coordinated by Colliers', '', 'fuller.ejf@gmail.com', 'Pitched previously'),
('David Flaherty', 'CEO', 'flco.com', '', '', '', 'HOT', '', NULL, '', 'PHX JAX', '', '', 'dflaherty@flco.com', 'Pitched previously'),
('Paul Bertozzi', 'President & CEO', 'liveoakcontracting.com', '', '', 'Partnership in progress', 'HOT', '', NULL, '', 'PHX JAX', '', '19046558404', 'paulb@liveoakcontracting.com', 'Pitched previously'),
('Marc Pincus', 'Founder', 'workplay.ventures', '', '', '', 'HOT', '', NULL, 'Burning Man', 'PHX JAX', '', '', 'mark@super.io', 'Pitched previously'),
('Lucy Rogers', 'Co-Founder', 'justusconnect.com', 'Tony Cho', '', 'Partnership in progress', 'HOT', '', NULL, 'Burning Man', 'PHX JAX', '', '', 'lucy@justusconnect.com', 'Pitched previously'),
('Matthew Chang', 'Principal & Founder', 'changrobotics.ai', 'Tony Cho', 'Michael Weil, Brendan McKeon', '', 'HOT', 'Sent investor email', '2025-04-22', 'LinkedIn Outreach', 'PHX JAX', '', '', 'matthew@changrobotics.ai', 'Existing Investor'),
('Joshua Pardue', 'Managing Member', 'GNP Development Partners, LLC', 'Tony Cho', 'Michael Weil, Brendan McKeon', 'Pitched', 'HOT', 'Sent investor email', '2025-04-22', '', 'PHX JAX', '', '', 'JoshPardue@gnpdev.com', 'Existing Investor'),
('Tim Chang', 'Co-Founder', 'The Portal', 'Tony Cho', 'Michael Weil, Brendan McKeon', 'Pitched', 'HOT', 'Sent investor email', '2025-04-22', '', 'PHX JAX', '', '', 'timechange7@gmail.com', 'Existing Investor'),
('Brad Palmer', 'Executive Chair', 'Palm Ventures, LLC', 'Tony Cho', 'Michael Weil, Brendan McKeon', '', 'HOT', 'Sent investor email', '2025-04-22', '', 'PHX JAX', '', '', 'bpalmer@palmventures.com', 'Existing Investor'),
('Carleton Shephard', 'Founder', 'insiderexpeditions.com', 'Tony Cho', 'Michael Weil, Brendan McKeon', '', 'HOT', 'Sent investor email', '2025-04-22', '', 'PHX JAX', '', '', 'cshephard@insiderexpeditions.com', 'Existing Investor'),
('RJ Miller', 'President', 'GHC Housing Partners', 'Tony Cho', 'Michael Weil, Brendan McKeon', 'Pitched', 'HOT', 'Sent investor email', '2025-04-22', '', 'PHX JAX', '', '', 'rjmiller@ghchousing.com', 'Existing Investor'),
('Dave Gorson', 'Principal', 'Vantage Capital Partners LLC', 'Tony Cho', 'Michael Weil, Brendan McKeon', '', 'HOT', 'Sent investor email', '2025-04-22', '', 'PHX JAX', '', '', 'dgorson@gmail.com', 'Existing Investor'),
('Bryan Clontz', 'President', 'Charitable Solutions, LLC', 'Tony Cho', 'Michael Weil, Brendan McKeon', 'Pitched', 'HOT', 'Sent investor email', '2025-04-22', '', 'PHX JAX', '', '', 'bryan@charitablesolutionsllc.com', 'Existing Investor'),
('David Shaw', 'Managing Partner', 'blackpointgroup.com', 'Tony Cho', 'Michael Weil, Brendan McKeon', '', 'HOT', 'Sent investor email', '2025-04-22', '', 'PHX JAX', '', '', 'dshaw@blackpointgroup.com', 'Existing Investor'),
('Brock McClane', 'Member', 'bmdllc.com', 'Tony Cho', 'Michael Weil, Brendan McKeon', '', 'HOT', 'Email', '2025-04-22', '', 'PHX JAX', '', '', 'jbmcclane@bmdpl.com', 'Existing Investor'),
('Bear Kittay', '', '', 'Tony Cho', 'Michael Weil, Brendan McKeon', '', '', '', NULL, '', 'PHX JAX', '', '', 'bear@kittay.com', 'Existing Investor'),
('Shaurya Mehta', 'Associate', 'workplay.ventures', '', '', 'Declined', 'WARM', 'Email', NULL, '', '', '', '', 'shaurya@workplay.ventures', 'Pitched previously'),
('Dan Herdoon', 'Founder', 'kreatehub.com', 'Michael Weil', '', 'Declined', 'WARM', 'Email', NULL, '', 'PHX JAX', '', '', 'dan@kreatehub.com', 'Pitched previously'),
('David Miller', 'Co-founder', 'brightway.com', 'Michael Weil', '', 'Declined', '', '', NULL, 'Jodie Leach', 'PHX JAX', '', '19042943913', 'david@millerfamilies.org', 'Pitched previously'),
('Michael Dubow', '', '', '', '', 'Declined', '', '', NULL, 'Jodie', 'PHX JAX', 'Philanthropists; Susan on the Cummer Museum Board', '', 'midubow@gmail.com', 'Pitched previously'),
('Jeff Klotz', 'CEO', 'theklotzcompanies.com', 'Tony Cho', '', 'Reviewing docs/data room', '', '', NULL, 'PR', 'PHX JAX', '', '19045141090', 'jklotz@theklotzcompanies.com', 'Pitched previously'),
('Jason Schulist', 'CEO & Founder', 'Grazing Lands Conservation Initiative', 'Tony Cho', '', 'Scheduled Pitch', 'COLD', 'Email', '2025-01-22', 'Olivier GIRARD', 'PHX JAX', '', '', 'schulistj@gmail.com', 'Pitched previously'),
('Max Dempsey', '', '', 'Tony Cho', 'Michael Weil', '', 'COLD', 'In person', NULL, '', 'PHX JAX', '', '', 'max2016@gmail.com', 'Pitched previously'),
('Matt Wiggins', '', '', 'Tony Cho', '', '', 'COLD', 'Email', '2025-01-20', '', 'PHX JAX', 'Working on exiting OZ properties; needs 30-60 days to make OZB-OZF cash movements', '12037227943', 'mmwiggins@gmail.com', 'Pitched previously'),
('Charles Wiggins', 'CEO', 'Starseed Ventures', 'Tony Cho', 'Michael Weil', '', 'COLD', 'Email', '2025-01-20', '', 'PHX JAX', '', '', 'cwiggins@starseedpartners.com', 'Pitched previously'),
('Shirley Benaroch', 'Section 8 Multi-family Investor', '', 'Michael Weil', '', '', 'COLD', 'Email', '2025-01-23', 'Tony Cho', 'PHX JAX', '', '15148165864', 'benarochshirley@gmail.com', 'Pitched previously'),
('Sally Peebles', 'Partner', 'Vicente LLP', 'Michael Weil', '', '', 'COLD', 'Email', '2025-03-05', 'PHX JAX', 'PHX JAX', '', '19042671104', 'S.Peebles@VicenteLLP.com', 'Pitched previously'),
('Carlos Zegarra', 'Executive Director', 'sachamama.org', 'Tony Cho', 'Michael Weil', '', 'COLD', 'Email', '2025-02-12', '', 'PHX JAX', '', '19168334413', 'c.zegarra@sachamama.org', 'Pitched previously'),
('Sebastien Gault', 'Director, Wealth Manager', 'bny.com', 'Tony Cho', '', '', 'COLD', '', NULL, '', 'PHX JAX', '', '14074590205', 'sgault1@gmail.com', 'Pitched previously'),
('Asi Cymbal', 'CEO', 'Cymbal DLT Companies', 'Tony Cho', 'Brendan McKeon', '', 'COLD', 'Email', NULL, '', 'PHX JAX', '', '7864172806', 'Asi@CymbalDLT.com', 'Pitched previously'),
('Dillion Baynes', 'CEO', 'Colombia Ventures', 'Michael Weil', '', '', 'COLD', 'Phone call', '2025-01-23', 'Sam Middlekauf', 'PHX JAX', '', '14042291387', 'dbaynes@columbiaven.com', 'Pitched previously'),
('Garrett Navia', 'Managing Director', 'dagrosacp.com', 'Tony Cho', '', '', 'COLD', 'Zoom Call', '2025-03-19', '', 'PHX JAX', '', '13052139438', 'gnavia@lafamiliaadvisors.com', 'Pitched previously'),
('Paul Garner', 'Associate Director', 'eyzenberg.com', 'Tony Cho', 'Brendan McKeon', '', 'COLD', 'Email', '2025-03-28', 'LinkedIn Outreach', 'PHX JAX', '', '19859519220', 'pgarner@garnercre.com', 'Pitched previously'),
('Adriana Sanchez', 'Vice President', 'gs.com', 'Tony Cho', '', '', 'COLD', '', NULL, 'Danet Linares (Blancare)', 'PHX JAX', '', '13057551031', 'adriana.sanchez@gs.com', 'Pitched previously'),
('Bryce Sinnerz', 'CEO', 'Sinful Kidz Foundation', 'Tony Cho', '', '', 'COLD', 'In person', '2025-01-17', '', 'PHX JAX', 'Leadership team of Keystone Species Co.', '17026959889', 'Bryce@sinfulblendz.com', 'Pitched previously'),
('Ryan Cronk', 'Vice President, Development', 'flco.com', '', '', '', '', '', NULL, '', 'PHX JAX', '', '13176793854', 'rcronk@flco.com', 'Pitched previously'),
('Kathy Fettke', 'Co-Founder', 'realwealth.com', '', '', '', '', '', NULL, '', 'PHX JAX', '', '19259140810', 'kathy@realwealthnetwork.com', 'Pitched previously'),
('Aaron Meisenheimer', '', '', '', '', '', '', '', NULL, '', 'PHX JAX', '', '', '', 'Never been pitched'),
('Adam Krim', 'Managing Partner', 'thealignedgroup.com', '', '', '', '', '', NULL, 'Tony', 'PHX JAX', '', '', 'Adam@alignedgroup.com', 'Never been pitched'),
('Alberto Cassab', '', '', 'Tony Cho', '', '', '', '', NULL, 'Nadav', 'PHX JAX', '', '', '', 'Never been pitched'),
('Will Beilharz', 'Managing Partner', 'anura.earth', '', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'will@anura.earth', 'Pitched previously'),
('Jafar Shabani', '', 'DMCC Group', '', '', '', '', '', NULL, 'Carolina', 'PHX JAX', '', '', 'jafar@dmcmiami.com', 'Pitched previously'),
('Bay Bridge Advisors- Equity', '', '', '', '', '', '', '', NULL, '', 'PHX JAX', '', '', '', 'Never been pitched'),
('Jared Wisen', 'AVP, Investments', 'cimgroup.com', 'Brendan McKeon', '', '', '', '', NULL, '', 'PHX JAX', '', '14014504109', 'jwisen@cimgroup.com', 'Pitched previously'),
('Jeff Rosen', 'Principal', 'chance-partners.com', '', 'Brendan McKeon', '', '', '', NULL, 'Laura Gonzales', 'PHX JAX', '', '13107806248', 'jrosen@chance-partners.com', 'Pitched previously'),
('Michael Hosto', 'Licensed Property Claims Adjuster', 'rivercityclaims.com', 'Michael Weil', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'MichaelHosto@gmail.com', 'Pitched previously'),
('Richard Powell', 'Executive Chairman', 'apch.com', '', '', '', '', '', NULL, '', 'PHX JAX', '', '16178273823', 'rpowell@apch.com', 'Never been pitched'),
('Eduardo Emanuelli', 'Founder', 'efpublicrelations.com', '', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'eduardo@efgrouppr.com', 'Never been pitched'),
('Gaudi Castro', 'Co Founder/ Partner', 'Native Construction Group', 'Brendan McKeon', '', '', '', '', NULL, '', 'PHX JAX', '', '17863030369', 'gcastro@native-cg.com', 'Pitched previously'),
('Erez Hevroni', 'CEO', 'innotech-ib.com', 'Brendan McKeon', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'erez@innotech-ib.com', 'Pitched previously'),
('David Smith', 'Founder/ Principal', 'lgcapitalpartners.com', 'Brendan McKeon', '', '', '', '', NULL, '', 'PHX JAX', '', '13056134818', 'david@lgcapitalpartners.com', 'Pitched previously'),
('Robert Kaplan', 'Executive Managing Director', 'cushmanwakefield.com', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '13057945672', 'robert.kaplan@cushwake.com', 'Pitched previously'),
('David Buttrey', 'Managing Partner', 'dtbadvisors.com', '', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'david@dtbadvisors.com', 'Pitched previously'),
('Brian Pearl', 'Principal', 'globalcity.co', 'Brendan McKeon', '', '', '', '', NULL, '', 'PHX JAX', '', '13059725126', 'bpearl@globalcity.co', 'Pitched previously'),
('Jon Wiener', 'Senior Director', 'silverarchcp.com', 'Brendan McKeon', '', '', '', '', NULL, '', 'PHX JAX', '', '12012542559', 'jonathanweiner@silverarchcp.com', 'Pitched previously'),
('Don Wenner', 'CEO', 'dlpcapital.com', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '18003508061', 'don@dlpcapital.com', 'Pitched previously'),
('Jeff Hammer', 'CEO / Founder', 'forteimpactadvisors.com', 'Tony Cho', 'Brendan McKeon, Michael Weil', '', '', '', NULL, '', 'PHX JAX', '', '', 'jeff@hammerforte.com', 'Pitched previously'),
('Greg Stuppler', 'CEO', 'surf.capital', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'greg@surf.capital', 'Pitched previously'),
('Laura Di Bella', 'Government Relations Advisor', 'adamsandreese.com', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '18506558933', 'laura.dibella@arlaw.com', 'Pitched previously'),
('David Centner', 'Chairman', 'dlccapmgmt.com', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'david@centner.com', 'Pitched previously'),
('Piers Dunhill', 'Founder', 'Dunhill Ventures', '', '', '', '', '', NULL, '', 'PHX JAX', 'Dunhill Ventures', '', 'pd@dunhillventures.io', 'Never been pitched'),
('Jim Gilmore', 'lobbyist', 'Southern Group', 'Michael Weil', '', '', '', '', NULL, 'Emily Pierce', 'PHX JAX', '', '19045910975', 'gilmore@thesoutherngroup.com', 'Pitched previously'),
('Bryan Moll', 'CEO', 'Gateway', 'Tony Cho, Michael Weil', '', '', '', '', NULL, 'Tony', 'PHX JAX', '', '', 'bmoll@gatewayjax.com', 'Pitched previously'),
('Kay Ehas', 'CEO, Groundwork Jax', 'Groundwork Jax', 'Tony Cho', '', '', '', '', NULL, 'Tony', 'PHX JAX', '', '19044010453', 'kay@groundworkjacksonville.org', 'Pitched previously'),
('Ellen Wiss', 'Co-Founder and Board Chair', 'readusainc.com', 'Michael Weil', '', '', '', '', NULL, 'Jodie and Kerrie', 'PHX JAX', '', '', 'ellen@readusainc.com', 'Pitched previously'),
('Dennis Whittle', 'CEO', 'Jacksonville Civic Council', 'Michael Weil', '', '', '', '', NULL, 'Jodie', 'PHX JAX', '', '', 'dennis@jaxciviccouncil.com', 'Pitched previously'),
('Alex Cranberg', 'Chairman', 'aspectenergy.com', 'Tony Cho', '', '', '', '', NULL, 'Tripp Guiliford', 'PHX JAX', '', '', 'acranberg@aspectenergy.com', 'Never been pitched'),
('Cindy Edelman', '', '', '', '', '', '', '', NULL, 'Kerrie', 'PHX JAX', 'Philanthropist, art collector', '', 'cindyedelman@gmail.com', 'Never been pitched'),
('Daniel Davis', 'President and CEO', 'jaxchamber.com', '', '', '', '', '', NULL, 'Emily', 'PHX JAX', 'Chamber President', '19043666660', 'Daniel.Davis@jaxchamber.com', 'Never been pitched'),
('Preston Haskell', 'Founder', 'haskell.com', 'Tony Cho', '', '', '', '', NULL, 'Kerrie', 'PHX JAX', '', '', 'Preston.Haskell@haskell.com', 'Pitched previously'),
('Brian Wolfburg', 'President & CEO', 'vystarcu.org', 'Michael Weil', '', '', '', '', NULL, 'Jodie/Kerrie', 'PHX JAX', 'SVP, Foundation President, Vystar; MOCA Board Member', '19049082500', 'wolfburgb@vystarcu.org', 'Pitched previously'),
('Isiah Oliver', 'President', 'jaxcf.org', '', '', '', '', '', NULL, 'Michael Dubow (Jodie)', 'PHX JAX', 'Community Foundation of NE FL, President', '', 'ioliver@jaxcf.org', 'Pitched previously'),
('Brian Parks', 'Head of Wholesale Banking', 'amerisbank.com', 'Michael Weil', '', '', '', '', NULL, 'David Miller', 'PHX JAX', '', '19046122055', 'Brian.Parks@amerisbank.com', 'Pitched previously'),
('Laura Gonzales', 'Principal', 'aheadconsultingsolutions.com', '', '', 'Pitched', '', '', NULL, '', 'PHX JAX', '', '19047182256', 'laura@aheadconsultingsolutions.com', 'Pitched previously'),
('Shervin Pishevar', 'Investor', 'pishevar.com', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'shervin@pishevar.com', 'Pitched previously'),
('Steve Rhodes', '', '', 'Tony Cho', '', '', '', '', NULL, '', 'Brickell, PHX JAX', '', '13057991407', 'SteveRhodesMiami@gmail.com', 'Pitched previously'),
('Sergio Rok', 'President', 'rokacquisitions.com', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '13053774921', 'sergio@rokenterprisesinc.com', 'Pitched previously'),
('Doug Levine', 'CEO', 'bigmoveproperties.com', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '17868775322', 'levine.doug@gmail.com', 'Pitched previously'),
('Chad McWhinney', 'CEO, Chairman & Co-Founder', 'realberry.com', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX, Brickell', '', '', 'ccm@mcwhinney.com', 'Pitched previously'),
('Scott Beecham', 'VP, Development', 'communitymodular.com', '', '', '', '', '', NULL, '', 'PHX JAX', '', '12087139566', 'sbeecham@indiedwell.com', 'Pitched previously'),
('Ian Zinn', 'Principal', 'bernstein.com', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '16178238421', 'Ian.Zinn@bernstein.com', 'Pitched previously'),
('Ryan Fletcher', 'CEO', 'vibrantbt.com', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'ryan@vibrantbt.com', 'Pitched previously'),
('Kevin Fishner', 'Owner', 'eatradius.com', 'Brendan McKeon', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'kfishner@gmail.com', 'Pitched previously'),
('Andy Allen', 'CEO & Cofounder', 'cornerlotdevelopment.com', 'Tony Cho', '', '', '', '', NULL, '', '', '', '', 'aallen@cornerlotdevelopment.com', 'Pitched previously'),
('Alex Sefakis', 'President', 'jwbrealestatecapital.com', 'Tony Cho', '', '', '', '', NULL, '', '', '', '19045666400', 'Alex@jwbcompanies.com', 'Pitched previously'),
('Jean Reiminger', 'Vice President', 'quilvestcapital.com', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'Jean.reiminger@gmail.com', 'Pitched previously'),
('Eric Fingleson', 'Sr. Vice President', 'UBS Pacific Peak', 'Tony Cho', '', '', '', '', NULL, '', '', '', '13108595638', 'eric.fingleson@ubs.com', 'Pitched previously'),
('Patti McElroy', 'Senior Vice President', 'vystarcu.org', '', '', '', '', '', NULL, 'Jodie/Kerrie', 'PHX JAX', 'SVP, Foundation President, Vystar; MOCA Board Member', '19049082915', 'mcelroyp@vystarcu.org', 'Pitched previously'),
('Kerrie Slattery', 'Fundraising Consultant', 'K. Slattery Consulting', '', '', '', '', '', NULL, '', 'PHX JAX', '', '19042339022', 'kerrie@kslatteryconsulting.com', 'Pitched previously'),
('Wanda Willis', '', 'Community Foundation of NE FL', '', '', '', '', '', NULL, 'Emily', 'PHX JAX', 'VP Civic Leadership', '', 'WWillis@jaxcf.org', 'Pitched previously'),
('Darnell Smith', 'Market President', 'floridablue.com', '', '', '', '', '', NULL, 'kerrie', 'PHX JAX', 'North Market President, Florida Blue', '', 'Darnell.Smith@bcbsfl.com', 'Pitched previously'),
('Mari Kuraishi', 'President', 'dupontfund.org', 'Michael Weil', '', '', '', '', NULL, 'Kerrie and Jodie', 'PHX JAX', 'Jesse Ball Dupont Fund, CEO', '', 'mkuraishi@dupontfund.org', 'Pitched previously'),
('Nathaniel Ford', 'CEO', 'jtafla.com', '', '', '', '', '', NULL, 'Suzanne Pickett', 'PHX JAX', 'CEO, JTA', '', 'nford@jtafla.com', 'Pitched previously'),
('Brian Murray', 'CEO', 'shiftcapital.us', 'Tony Cho', 'Michael Weil', '', '', '', NULL, '', 'PHX JAX', '', '19176997347', 'brian@shiftcapital.us', 'Pitched previously'),
('Britt Morgan-Saks', 'CEO & Cofounder', 'thejune.club', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '16464683299', 'britt@thejunegrp.com', 'Pitched previously'),
('George Vail', 'Principal', 'avisonyoung.com', 'Brendan McKeon', '', '', '', '', NULL, '', 'PHX JAX', '', '13054587487', 'george.vail@avisonyoung.com', 'Pitched previously'),
('Jay Massirman', 'CEO & Founder', 'rivergatere.com', '', '', '', '', '', NULL, 'Tony', 'PHX JAX', '', '13057538889', 'jay@rivergatere.com', 'Pitched previously'),
('Bernie Cahill', 'Partner', 'activist.co', 'Tony Cho', '', '', '', '', NULL, 'Tony', 'PHX JAX', '', '13107462000', 'cahill@activist.co', 'Pitched previously'),
('Jason Cotter', 'Managing Principal', 'eloise-capital.com', 'Tony Cho', '', '', '', '', NULL, 'Tony', 'PHX JAX', '', '17024495655', 'jason.cotter@eloise-capital.com', 'Pitched previously'),
('Tatiana Kazakova', 'Co Founder', 'Leaders on Purpose', '', '', '', '', '', NULL, '', 'PHX JAX', 'Connected to investors who may be interested in funding', '', 'tatiana@leadersonpurpose.com', 'Pitched previously'),
('Lynn Isenberg', 'Founder', 'lynnisenberg.com', '', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'lynn@lynnisenberg.com', 'Never been pitched'),
('Bill Reed', 'Principal', 'regenesisgroup.com', 'Tony Cho', '', '', '', '', NULL, 'Tony Cho', 'PHX JAX', '', '16177976099', 'Bill@place.fund', 'Pitched previously'),
('Henning von Kalm', '', '', '', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'vonkalm@gmail.com', 'Never been pitched'),
('Julie Giancola', '', '', '', '', '', '', '', NULL, '', 'PHX JAX', '', '8592400728', 'julie@creativeequityfunds.com', 'Never been pitched'),
('Les Lyons', '', '', '', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'relyons2020@gmail.com', 'Never been pitched'),
('Roland Kassis', 'Founder', 'kassis.co', '', 'Tony Cho', '', '', '', NULL, 'Carolina', 'PHX JAX', '', '', 'roland@kassis.ventures', 'Never been pitched'),
('Tony DeRosa', 'President', 'westvest.com', 'Tony Cho', '', '', '', '', NULL, 'Tony', 'PHX JAX', '', '13054904610', 'tony@westvest.com', 'Never been pitched'),
('Ballentine Partners', '', '', '', '', '', '', '', NULL, 'Jay', 'PHX JAX', '', '', '', 'Never been pitched'),
('Abel Harding', 'Market President', 'firsthorizon.com', 'Michael Weil', '', '', '', '', NULL, '', 'PHX JAX', '', '19045354781', 'abel.harding@firsthorizon.com', 'Pitched previously'),
('Sherry McGill', 'President & COO', 'dupontfund.org', '', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'sherrymagill@mac.com', 'Pitched previously'),
('Karen Feagins', 'VP, Client and Community Relations Director', 'pnc.com', '', '', '', '', '', NULL, 'Kerrie', 'PHX JAX', 'VP Client and Community Relations, PNC', '', 'karen.feagins@pnc.com', 'Pitched previously'),
('Ann Marie Knight', 'Vice President, Community Engagement', 'ufhealthjax.org', '', '', '', '', '', NULL, '', 'PHX JAX', '', '19042444785', 'Ann-Marie.Knight@jax.ufl.edu', 'Pitched previously'),
('Erin Gordon', 'CEO', 'fisheragency.com', '', '', '', '', '', NULL, '', 'PHX JAX', '', '19045534092', 'erin@fisheragency.com', 'Pitched previously'),
('Julie Dennis', 'CEO', 'ovidsolutions.net', '', '', '', '', '', NULL, 'Jim Gilmore', 'PHX JAX', '', '18504451932', 'julie@ovidsolutions.net', 'Pitched previously'),
('Clayton Louis Ferrara', 'CEO', 'Ideas for Us', '', '', '', '', '', NULL, 'Tony', 'PHX JAX', '', '', 'clay@ideasforus.org', 'Pitched previously'),
('Eric Mulata', 'Vice President, Development', 'dalianllc.com', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '12027256486', 'emulata@daliandevelopment.com', 'Pitched previously'),
('Jason Halpern', 'Principal', 'jmhdev.com', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '', 'jason@jmhdev.com', 'Pitched previously'),
('William Colledge', 'Winn Dixie Family/Tallyrand Owner', '', '', '', '', '', '', NULL, '', 'PHX JAX', '', '19043058018', 'wlcolledge@gmail.com', 'Pitched previously'),
('Charles Salice', '', '', 'Tony Cho', '', '', '', '', NULL, '', 'PHX JAX', '', '13233333404', 'nfps@me.com', 'Pitched previously'),
('Seth Gadinsky', '', 'gadinsky.com', '', '', 'Follow up requested', '', '', NULL, '', '', '', '', 'Seth@gadinsky.com', 'Pitched previously'),
('Lori Ann Santamaria', '', '', '', '', 'Pitched', '', '', NULL, '', '', '', '', 'loriannsantamaria@gmail.com', ''),
('Omani Carson', '', '', '', '', '', '', '', NULL, '', '', '', '', '', '');
